#!/usr/bin/awk -f

BEGIN 					{FS = ":";
						}

/%THE/ 			 		{for(i=2; i<NF;i++){
						 	if($i ~/</){
						 		split($i,b,"<");
						 		
						 		if(b[1] ~/_/){
						 			split(b[1],c,"_")
							 		print "Relações -> " c[1] " " c[2];	
						 		}
						 		else{
						 			print "Relações -> " b[1];
						 		}
						 	}
						 	else{
						 		if($i ~/_/){
						 			split($i,c,"_")
						 			print "Relações -> " c[1] " " c[2]
						 		}
						 		else{
						 			print "Relações -> " $i;
						 		}
						 	}
						 } 
						
						}


/%dom/					{print "Dominio -> "$2}
/%inv/					{if($2 ~/_/){
							split($2,c,"_")
						 	print "Relações -> " c[1] " " c[2]
							}
						 else{
						 	print "Relações -> " $2
						 }
						 if($3 ~/_/){
							split($3,c,"_")
						 	print "Relações -> " c[1] " " c[2]
						 	}
						 else{
						 	print "Relações -> " $3
						 }
						}