#!/usr/bin/awk -f
# cria ficheiros html ?? a ver

BEGIN 					{FS = ":";
						}

/%inv/					{for(i=2; i<=(i+3);i++){
							if($i ~/_/){
								gsub("_"," ",$i)
								inv[i] = $i
							}
							else{
						 		inv[i]=$i;
						 	}	
						 }
						 for(x in inv) print inv[x]
						}

/%THE/					{split($2,a,"<")}
/%THE/					{for(i=1 ; i<=NF; i++){
							if($i ~/_/){
								gsub("_"," ",$i)
								b[i-1] = $i
							}
							else{
								b[i-1]=$i;
							}
						 }
						 for(x in b) print b[x]
						}

#/%THE/ matches lines having this text, as well as /%%/ does.
/%THE/					{flag = 1; next} 	#sets the flag when the text %THE is found. Then, it skips the line.
/%%/					{flag = 0}	    #unsets the flag when the text %% is found.

# maior que dois pois ha campos com 2 espaços e imprimia na mesma... para corrigir pode ser verificar se no espaço existe letras\


flag && $0!~/[%#]/			{for(i=1; i<=NF; i++){
							 	if(length($i)>2){
							 		if(i == 1 && b[i-1] ~/</){
										split(b[i-1],c,"<")
										if(b[i-1]~/%/){
											split($i,g,"|")
											for(x in g) print "(" $1 "," , "iof" ",", c[2]")"
										}
									}
									if(b[i-1] ~/</ && b[i-1]!~/THE/){
										split(b[i-1],c,"<")
										split($i,g,"|")
										for(x in g) print "(" $1 "," , c[1] ",", g[x]")"							
										print "(" g[x] "," , "iof" ",", c[2]")"
									}
									else{
										if(b[i-1]!~/THE/){
											split($i,g,"|")
											for(x in g) print "(" $1 "," , b[i-1] ",", g[x]")"
										}
									}
								}
							 }
							}

